---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipeline-environments-triggers-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-pipeline-environments-triggers-el-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: tekton-pipeline-environments-triggers-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-pipeline-environments-triggers-el-clusterbinding
subjects:
- kind: ServiceAccount
  name: tekton-pipeline-environments-triggers-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
---
apiVersion: v1
kind: Secret
metadata:
  name: tekton-pipeline-environments-github-secret
  namespace: default
type: Opaque
stringData:
  secretToken: "7654321"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: tekton-pipeline-environments-listener
  namespace: default
spec:
  triggers:
    - name: main-dev-push-events
      interceptors:
        - ref:
            name: github
          params:
            - name: secretRef
              value:
                secretName: tekton-pipeline-environments-github-secret
                secretKey: secretToken
            - name: eventTypes
              value: ["push"]
        - name: "only on main"
          ref:
            name: cel
          params:
            - name: filter
              value: "body.ref == 'refs/heads/main'"
        - name: "only on 'demo' directory changes"
          ref:
            name: cel
          params:
            - name: filter
              value: >
                body.head_commit.added.exists(x, x.startsWith('dev/')) ||
                body.head_commit.removed.exists(x, x.startsWith('dev/')) ||
                body.head_commit.modified.exists(x, x.startsWith('dev/'))
      bindings:
        - ref: github-push-binding
      template:
        ref: dev-pipeline-trigger-template
    - name: main-staging-push-events
      interceptors:
        - ref:
            name: github
          params:
            - name: secretRef
              value:
                secretName: tekton-pipeline-environments-github-secret
                secretKey: secretToken
            - name: eventTypes
              value: ["push"]
        - name: "only on main"
          ref:
            name: cel
          params:
            - name: filter
              value: "body.ref == 'refs/heads/main'"
        - name: "only on 'demo' directory changes"
          ref:
            name: cel
          params:
            - name: filter
              value: >
                body.head_commit.added.exists(x, x.startsWith('staging/')) ||
                body.head_commit.removed.exists(x, x.startsWith('staging/')) ||
                body.head_commit.modified.exists(x, x.startsWith('staging/'))
      bindings:
        - ref: github-push-binding
      template:
        ref: staging-pipeline-trigger-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-pipeline-environments-triggers-sa
            containers:
              - resources:
                  requests:
                    memory: 64Mi
                    cpu: 250m
                  limits:
                    memory: 128Mi
                    cpu: 500m
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-pipeline-environments-el
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - tekton-pipeline-environments-el.russparmer.dev
    secretName: tekton-pipeline-environments-el-tls
  rules:
  - host: tekton-pipeline-environments-el.russparmer.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: el-tekton-pipeline-environments-listener
            port:
              name: http-listener
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: flux-event-listener
  namespace: default
spec:
  triggers:
    - name: flux-event
      # interceptors: []
      bindings:
        - ref: flux-binding
      template:
        ref: flux-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-pipeline-environments-triggers-sa
            containers:
              - resources:
                  requests:
                    memory: 64Mi
                    cpu: 250m
                  limits:
                    memory: 64Mi
                    cpu: 250m
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flux-el
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - flux-el.russparmer.dev
    secretName: flux-el-tls
  rules:
  - host: flux-el.russparmer.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: el-flux-event-listener
            port:
              name: http-listener