---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: promote-to-environment
  namespace: default
spec:
  params:
    - name: source-git-url
      type: string
    - name: source-git-revision
      type: string
    - name: source-git-directory
      type: string
      default: ""
    - name: source-git-files
      type: string
      default: "."
    - name: destination-git-url
      type: string
    - name: destination-git-full-name
      type: string
    - name: destination-git-directory
      type: string
      default: ""
    - name: destination-git-branch
      type: string
    - name: destination-git-clone-revision
      type: string
      default: main
  workspaces:
    - name: shared-data
  tasks:
    - name: clone-source
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.source-git-url)
        - name: revision
          value: $(params.source-git-revision)
        - name: subdirectory
          value: source
      workspaces:
        - name: output
          workspace: shared-data
          subPath: source
    - name: clone-destination
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.destination-git-url)
        - name: revision
          value: $(params.destination-git-clone-revision)
        - name: subdirectory
          value: destination
      workspaces:
        - name: output
          workspace: shared-data
          subPath: destination
    - name: copy-files-to-destination
      taskRef:
        name: move-files
      runAfter:
        - clone-source
        - clone-destination
      params:
        - name: source-files
          value: $(params.source-git-files)
        - name: destination-dir
          value: $(params.destination-git-directory)
        - name: destination-branch
          value: $(params.destination-git-branch)
      workspaces:
        - name: source
          workspace: shared-data
          subPath: source
        - name: destination
          workspace: shared-data
          subPath: destination
    - name: open-pr
      taskRef:
        name: github-open-pr
        kind: ClusterTask
      runAfter:
        - copy-files-to-destination
      params:
        - name: REPO_FULL_NAME
          value: $(params.destination-git-full-name)
        - name: HEAD
          value: $(params.destination-git-branch)
        - name: BASE
          value: $(params.destination-git-revision)
        - name: TITLE
          value: "pipeline testing"
        - name: BODY
          value: "some pr message"
        - name: GITHUB_TOKEN_SECRET_NAME
          value: github-api-token
