---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: dev-pipeline-trigger-template
  namespace: default
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: git-full-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: promote-to-environment-staging-run-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: promote-to-environment
        params:
          - name: source-git-url
            value: $(tt.params.git-url)
          - name: source-git-revision
            value: $(tt.params.git-revision)
          - name: source-git-directory
            value: dev
          - name: destination-git-url
            value: $(tt.params.git-url)
          - name: destination-git-full-name
            value: $(tt.params.git-full-name)
          - name: destination-git-directory
            value: staging
          - name: destination-git-branch
            value: release-staging
          - name: deployment-namespace
            value: staging
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          # - name: config-data
          #   configmap:
          #     name: dev-pipeline-config
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: staging-pipeline-trigger-template
  namespace: default
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: git-full-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: promote-to-environment-prod-run-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: promote-to-environment
        params:
          - name: source-git-url
            value: $(tt.params.git-url)
          - name: source-git-revision
            value: $(tt.params.git-revision)
          - name: source-git-directory
            value: staging
          - name: destination-git-url
            value: $(tt.params.git-url)
          - name: destination-git-full-name
            value: $(tt.params.git-full-name)
          - name: destination-git-directory
            value: prod
          - name: destination-git-branch
            value: release-prod
          - name: deployment-namespace
            value: prod
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: flux-template
  namespace: default
spec:
  params:
    - name: body
    - name: severity
    - name: message
    - name: reason
    - name: revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: flux-run-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: flux
        params:
          - name: body
            value: $(tt.params.body)
          - name: severity
            value: $(tt.params.severity)
          - name: message
            value: $(tt.params.message)
          - name: reason
            value: $(tt.params.reason)
          - name: revision
            value: $(tt.params.revision)
        # workspaces:
        #   - name: shared-data
        #     volumeClaimTemplate:
        #       spec:
        #         accessModes:
        #           - ReadWriteOnce
        #         resources:
        #           requests:
        #             storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
  namespace: default
spec:
  params:
    - name: git-revision
      value: $(body.head_commit.id)
    - name: git-url
      value: $(body.repository.clone_url)
    - name: git-full-name
      value: $(body.repository.full_name)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: flux-binding
  namespace: default
spec:
  params:
    - name: body
      value: $(extensions.body)
    - name: severity
      value: $(body.severity)
    - name: message
      value: $(body.message)
    - name: reason
      value: $(body.reason)
    - name: revision
      value: $(body.metadata.revision)
    - name: kind
      value: $(body.involvedObject.kind)
    - name: name
      value: $(body.involvedObject.name)
    - name: namespace
      value: $(body.involvedObject.namespace)
