---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tekton
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/rparmer/tekton.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-core
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: tekton
  path: ./install/core
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-dashboard
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: tekton-core
  sourceRef:
    kind: GitRepository
    name: tekton
  path: ./install/dashboard
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-config
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: tekton-core
  sourceRef:
    kind: GitRepository
    name: tekton
  path: ./install/config
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-clustertasks
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: tekton-core
  sourceRef:
    kind: GitRepository
    name: tekton
  path: ./clustertasks
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-pipelines
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: tekton-core
    - name: tekton-clustertasks
  sourceRef:
    kind: GitRepository
    name: tekton
  path: ./pipelines
  prune: true
  validation: client
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tekton-pipeline-environments
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/rparmer/tekton-pipeline-environments.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-pipeline-environments
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: tekton-pipeline-environments
  prune: true
  validation: client
