apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
  namespace: default
secrets:
  - name: basic-user-pass
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  namespace: default
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: token
  password: <github_api_token>
---
apiVersion: v1
kind: Secret
metadata:
  name: github-api-token
  namespace: default
type: Opaque
stringData:
  token: <github_api_token>
