---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-pipeline
  namespace: default
spec:
  params:
    - name: source-git-url
    - name: source-git-revision
    - name: destination-git-url
    - name: destination-git-full-name
    - name: destination-git-revision
      default: main
    - name: destination-git-master-branch
      default: main
    - name: image-name
    - name: image-tag
      default: latest
    - name: path-to-image-context
      default: ./
    - name: path-to-dockerfile
      default: ./Dockerfile
  workspaces:
    - name: source-data
    - name: destination-data
    - name: docker-credentials
  tasks:
    - name: clone-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.source-git-url)
        - name: revision
          value: $(params.source-git-revision)
      workspaces:
        - name: output
          workspace: source-data
    - name: clone-destination
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.destination-git-url)
        - name: revision
          value: $(params.destination-git-revision)
        - name: depth
          value: 0
      workspaces:
        - name: output
          workspace: destination-data
    # TODO: add test
    - name: build-image
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.image-name):$(params.image-tag)
        - name: CONTEXT
          value: $(params.path-to-image-context)
        - name: DOCKERFILE
          value: $(params.path-to-dockerfile)
      runAfter:
        - clone-source
      workspaces:
        - name: source
          workspace: source-data
        - name: dockerconfig
          workspace: docker-credentials
    # TODO: add image scan
    - name: copy-files-to-destination
      taskRef:
        name: move-files
      runAfter:
        - clone-source
        - clone-destination
        - build-image
      params:
        - name: source-files
          value: demo.yaml
        - name: destination-dir
          value: dev
        - name: destination-branch
          value: tekton-pipelines
      workspaces:
        - name: source
          workspace: source-data
        - name: destination
          workspace: destination-data
    - name: open-pr
      taskRef:
        kind: Task
        name: github-open-pr
      runAfter:
        - copy-files-to-destination
      params:
        - name: REPO_FULL_NAME
          value: $(params.destination-git-full-name)
        - name: HEAD
          value: tekton-pipelines
        - name: BASE
          value: $(params.destination-git-master-branch)
        - name: TITLE
          value: "pipeline testing"
        - name: BODY
          value: "some pr message"
        - name: GITHUB_TOKEN_SECRET_NAME
          value: github-api-token
