apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: sample-pipeline-trigger-template
  namespace: default
spec:
  params:
    - name: git-revision
      description: The git revision
      default: main
    - name: git-url
      description: The git repository url
    - name: image-name
      default: ghcr.io/rparmer/tekton
    - name: image-tag
      default: latest
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: sample-pipeline-run-
      spec:
        serviceAccountName: tekton-triggers-example-sa
        pipelineRef:
          name: sample-pipeline
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: image-name
            value: $(tt.params.image-name)
          - name: image-tag
            value: $(tt.params.image-tag)
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: docker-credentials
            secret:
              secretName: ghcr-credentials
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
  namespace: default
spec:
  params:
    - name: git-revision
      value: $(body.head_commit.id)
    - name: git-url
      value: $(body.repository.clone_url)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-pr-binding
spec:
  params:
    - name: git-revision
      value: $(body.pull_request.head.sha)
    - name: git-url
      value: $(body.repository.clone_url)
