apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: sample-pipeline-trigger-template
  namespace: default
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: destination-git-url
      default: https://github.com/rparmer/tekton-pipeline-environments.git
    - name: destination-git-full-name
      default: rparmer/tekton-pipeline-environments
    - name: image-name
      default: ghcr.io/rparmer/tekton
    - name: image-tag
      default: latest
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: sample-pipeline-run-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: sample-pipeline
        params:
          - name: source-git-url
            value: $(tt.params.git-url)
          - name: source-git-revision
            value: $(tt.params.git-revision)
          - name: destination-git-url
            value: $(tt.params.destination-git-url)
          - name: destination-git-full-name
            value: $(tt.params.destination-git-full-name)
          - name: image-name
            value: $(tt.params.image-name)
          - name: image-tag
            value: $(tt.params.image-tag)
        workspaces:
          - name: source-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteMany
                resources:
                  requests:
                    storage: 1Gi
          - name: destination-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteMany
                resources:
                  requests:
                    storage: 1Gi
          - name: docker-credentials
            secret:
              secretName: ghcr-credentials
          # - name: git-credentials
          #   secret:
          #     secretName: git-credentials
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
  namespace: default
spec:
  params:
    - name: git-revision
      value: $(body.head_commit.id)
    - name: git-url
      value: $(body.repository.clone_url)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-pr-binding
spec:
  params:
    - name: git-revision
      value: $(body.pull_request.head.sha)
    - name: git-url
      value: $(body.repository.clone_url)
