apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: getting-started-triggertemplate
  namespace: default
spec:
  params:
    - name: git-revision
      description: The git revision
      default: main
    - name: git-url
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
      default: default
    - name: image-tag
      default: latest
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: getting-started-pipeline-run-
        namespace: $(tt.params.namespace)
      spec:
        serviceAccountName: tekton-triggers-example-sa
        pipelineRef:
          name: getting-started-pipeline
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: image-tag
            value: $(tt.params.image-tag)
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: docker-credentials
            secret:
              secretName: ghcr-credentials
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: getting-started-pipelinebinding
  namespace: getting-started
spec:
  params:
    - name: git-revision
      value: $(body.head_commit.id)
    # - name: namespace
    #   value: default
    - name: git-url
      value: $(body.repository.clone_url)
