---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wego-pipeline-environment-promotion-trigger-sa
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wego-pipeline-environment-promotion-trigger-binding
  namespace: flux-system
subjects:
- kind: ServiceAccount
  name: wego-pipeline-environment-promotion-trigger-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wego-pipeline-environment-promotion-trigger-clusterbinding
subjects:
- kind: ServiceAccount
  name: wego-pipeline-environment-promotion-trigger-sa
  namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: wego-pipeline-environment-promotion
  namespace: flux-system
spec:
  triggers:
    - name: dev-deployment
      interceptors:
        - name: "ignore failed releases"
          ref:
            name: cel
          params:
            - name: filter
              value: "body.severity != 'error'"
        - name: "only listen to dev events"
          ref:
            name: cel
          params:
            - name: filter
              value: "body.involvedObject.namespace == 'dev'"
      bindings:
        - ref: wego-pipeline-environment-promotion-binding
        - name: source-git-directory
          value: dev
        - name: destination-git-directory
          value: staging
        - name: promotion-namespace
          value: staging
      template:
        ref: wego-pipeline-environment-promotion-template
    - name: staging-deployment
      interceptors:
        - name: "ignore failed releases"
          ref:
            name: cel
          params:
            - name: filter
              value: "body.severity != 'error'"
        - name: "only listen to staging events"
          ref:
            name: cel
          params:
            - name: filter
              value: "body.involvedObject.namespace == 'staging'"
      bindings:
        - ref: wego-pipeline-environment-promotion-binding
        - name: source-git-directory
          value: staging
        - name: destination-git-directory
          value: prod
        - name: promotion-namespace
          value: prod
      template:
        ref: wego-pipeline-environment-promotion-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: wego-pipeline-environment-promotion-trigger-sa
            containers:
              - resources:
                  requests:
                    memory: 64Mi
                    cpu: 250m
                  limits:
                    memory: 64Mi
                    cpu: 250m
