---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: flux
  namespace: default
spec:
  params:
    - name: body
    - name: severity
      type: string
    - name: message
      type: string
    - name: reason
      type: string
    - name: revision
      type: string
  # workspaces:
  #   - name: shared-data
    # - name: config-data
  tasks:
    - name: echo
      params:
        - name: body
          value: $(params.body)
        - name: severity
          value: $(params.severity)
        - name: message
          value: $(params.message)
        - name: reason
          value: $(params.reason)
        - name: revision
          value: $(params.revision)
      taskSpec:
        params:
          - name: body
          - name: severity
            type: string
          - name: message
            type: string
          - name: reason
            type: string
          - name: revision
            type: string
        steps:
          - image: ubuntu
            script: |
              echo "Body: $(params.body)"
              echo "Severity: $(params.severity)"
              echo "Message: $(params.message)"
              echo "Reason: $(params.reason)"
              echo "Revision: $(params.revision)"
